#!/bin/bash
# WF 2019-08-09
# update the controls from github
# Drag is not updated automatically since it has modifications
for control in Trackball Orbit
do
  js=${control}Controls.js 
  curl -s https://raw.githubusercontent.com/mrdoob/three.js/master/examples/js/controls/$js -o $js
done
